name: Lint & Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository https://github.com/actions/checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "1.13"

      - name: Run Go test
        run: |
          go test -race -v -coverprofile .coverage.txt ./...
          go tool cover -html=.coverage.txt -o .coverage.html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: .coverage.html
